export const SHOP_ROUTE = '/'
export const CART_ROUTE = '/cart'
export const ORDER_ROUTE = '/orders'
export const DEVICE_ROUTE = '/device'
export const CATEGORY_ROUTE = '/:category'
export const LOGIN_ROUTE = '/login'